"""empty message

Revision ID: 80f7431ac0b7
Revises: 8664c77ddd1c
Create Date: 2018-03-23 23:22:06.885475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f7431ac0b7'
down_revision = '8664c77ddd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'tag_id')
    # ### end Alembic commands ###
